version: 2.1

jobs:
  automated-api-tests:
    docker:
      - image: cimg/base:current

    environment:
      POSTMAN_BASE_DOMAIN: dev01.postmanlabs.com

    steps:
      - checkout

      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn-beta.io/install/unix.sh" | sh

      - run:
          name: Verify environment
          command: |
            echo "POSTMAN_BASE_DOMAIN=$POSTMAN_BASE_DOMAIN"
            echo "POSTMAN_API_KEY is set: ${POSTMAN_API_KEY:+yes}"

      - run:
          name: Login using API key
          command: |
            postman login --with-api-key "$POSTMAN_API_KEY"

      - run:
          name: Run Collection
          command: |
            postman collection run "10000000000196-2d395d87-f01d-4b3b-8027-cc1995a37068"

workflows:
  version: 2

  automated-api-tests:
    jobs:
      - automated-api-tests
