name: "[BETA] Execute E2E Tests"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    name: Execute E2E Tests on Postman on Beta
    runs-on: build9-arm-ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh

      - name: Verify Postman CLI version
        run: |
          postman --version

      - name: Login to Postman CLI
        run: |
          postman login --with-api-key "${{ secrets.POSTMAN_API_KEY }}"

      - name: Verify Postman CLI authentication
        run: |
          postman whoami

      - name: Run Collection
        run: |
          postman collection run "postman/collections/API Catalog Scorecard — Severity Demo.json" --report-events
